FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
# Установка dotnet-ef
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# Копирование и восстановление проекта
COPY ["UserService/UserService.csproj", "UserService/"]
RUN dotnet restore "UserService/UserService.csproj"
COPY . .
WORKDIR "/src/UserService"

# Используем отдельную команду только для миграций
ENTRYPOINT ["dotnet", "ef", "database", "update"]
